// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:news/api/model/sources/source.dart';
import 'package:news/api/model/sources/source_response.dart';
import 'package:news/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NewsAdapter());
    registerAdapter(NewsResponseAdapter());
    registerAdapter(SourceAdapter());
    registerAdapter(SourceResponseAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NewsAdapter());
    registerAdapter(NewsResponseAdapter());
    registerAdapter(SourceAdapter());
    registerAdapter(SourceResponseAdapter());
  }
}
